apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  root-password: Huiting123..
  database: fullstack
  user-name: test
  user-password: test